name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]  # Only one Python version for simplicity

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4  # Latest version of setup-python action
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Run flake8 (code style checks)
        run: |
          flake8 .  # Runs flake8 in the root directory

      - name: Run PyTest (unit tests)
        run: |
          pytest --maxfail=5 --disable-warnings  # Run tests and show warnings
