name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt  # Always install full dependencies

    - name: Lint with flake8
      run: |
        # Run flake8 with relaxed rules
        flake8 . --exit-zero --max-line-length=127 --statistics

    - name: Run tests with pytest
      run: |
        pytest --disable-warnings --maxfail=3  # Run up to 3 test failures for better debugging
